/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Androide;
import com.sv.udb.clases.ControladorAndroide;
import java.awt.HeadlessException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class Ejercicio1 extends javax.swing.JFrame {

    ControladorAndroide obj = new ControladorAndroide();
    List<Androide> androids;

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAndroide = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbTareas = new javax.swing.JComboBox<>();
        btnTarea = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstAndroides = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        btnDescendente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnPrimerosTres = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistListados = new javax.swing.JList<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(500, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Androide"));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 110));

        jLabel2.setText("Ingrese el nombre de androide:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtAndroide, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAndroide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tareas"));

        jLabel6.setText("Seleccione tarea:");

        cmbTareas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocinar", "Lavar carro", "Planchar", "Barrer", "Trapear" }));
        cmbTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTareasActionPerformed(evt);
            }
        });

        btnTarea.setText("Procesar");
        btnTarea.setEnabled(false);
        btnTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareaActionPerformed(evt);
            }
        });

        jLabel4.setText("Listado de Androides");

        jLabel7.setText("Vida de Androide:");

        lblPorcentaje.setText("Vida");

        jlstAndroides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlstAndroidesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jlstAndroides);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(17, 17, 17)
                        .addComponent(cmbTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnTarea)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lblPorcentaje))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnTarea))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Listados"));

        btnDescendente.setText("Ordenar por porcentaje de vida");
        btnDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescendenteActionPerformed(evt);
            }
        });

        jButton2.setText("Ordenar por más del 50%");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPrimerosTres.setText("Los 3 con más vida");
        btnPrimerosTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerosTresActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlistListados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnDescendente)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnPrimerosTres))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDescendente)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(btnPrimerosTres)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Agregar androide
        String nombre = txtAndroide.getText();
        int vida = 100;
        try {
            if (!"".equals(txtAndroide.getText())) {
                Androide androide = new Androide();
                androide.setsNombre(nombre);
                obj.agregarAndroide(androide, vida);
                JOptionPane.showMessageDialog(this, "Ha ingresado un nuevo androide", "Exito", JOptionPane.INFORMATION_MESSAGE);
                txtAndroide.setText("");
                lista(obj.obtenerAndroide());
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del Androide", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (HeadlessException ex) {
            System.err.println("Error inesperado al guardar " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTareasActionPerformed

    private void jlstAndroidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlstAndroidesMouseClicked
        //Al presionar en la lista
        Androide androide = jlstAndroides.getSelectedValue();
        lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
        btnTarea.setEnabled(true);
    }//GEN-LAST:event_jlstAndroidesMouseClicked

    private void btnTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareaActionPerformed
        Androide androide = new Androide();
        androide = jlstAndroides.getSelectedValue();
        //Asignar tarea a un androide
        switch (cmbTareas.getSelectedIndex()) {
            case 0:
                androide.setVida(androide.getVida() - 25);
                lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
                break;
            case 1:
                androide.setVida(androide.getVida() - 50);
                lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
                break;
            case 2:
                androide.setVida(androide.getVida() - 30);
                lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
                break;
            case 3:
                androide.setVida(androide.getVida() - 25);
                lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
                break;
            case 4:
                androide.setVida(androide.getVida() - 15);
                lblPorcentaje.setText(String.valueOf(androide.getVida()) + "%");
                break;
        }
        btnTarea.setEnabled(false);
    }//GEN-LAST:event_btnTareaActionPerformed

    private void btnDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescendenteActionPerformed
        // Ordenar de manera descendete segun su vida
        jlistListados.removeAll();
        listaDescendetemente(obj.ordenarDescendente());
    }//GEN-LAST:event_btnDescendenteActionPerformed

    private void btnPrimerosTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerosTresActionPerformed
        //Los 3 androides con más vida
        jlistListados.removeAll();
        List<Androide> androides = obj.obtenerAndroide();
        DefaultListModel<Androide> model = new DefaultListModel<>();
        for (Androide android : androides) {
            if (android.getVida() > 50) {
                model.addElement(android);
                if (model.getSize() == 3) {
                    break;
                }
            }
        }
        jlistListados.setModel(model);      
    }//GEN-LAST:event_btnPrimerosTresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Que tengan más del 50% de vida
        jlistListados.removeAll();
        List<Androide> androides = obj.obtenerAndroide();
        DefaultListModel<Androide> model = new DefaultListModel<>();
        for (Androide android : androides) {
            if (android.getVida() > 50) {
                model.addElement(android);
            }
        }
        jlistListados.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    private void lista(List<Androide> androids) {
        DefaultListModel<Androide> model = new DefaultListModel<>();
//        DefaultComboBoxModel<Androide> cmbModel = new DefaultComboBoxModel<>();
        for (Androide android : androids) {
            model.addElement(android);
        }
//        for (Androide android : androids) {
//            cmbModel.addElement(android);
//        }
        jlstAndroides.setModel(model);
        //jlistListados.setModel(model);
    }
    
    private void listaDescendetemente(List<Androide> androids) {
        DefaultListModel<Androide> model = new DefaultListModel<>();
        for (Androide android : androids) {
            model.addElement(android);
        }
        jlistListados.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDescendente;
    private javax.swing.JButton btnPrimerosTres;
    private javax.swing.JButton btnTarea;
    private javax.swing.JComboBox<String> cmbTareas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Androide> jlistListados;
    private javax.swing.JList<Androide> jlstAndroides;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JTextField txtAndroide;
    // End of variables declaration//GEN-END:variables

}
